# Generated by Django 2.2.5 on 2019-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanKredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('kepuasaan', models.IntegerField(max_length=225)),
                ('jumlah_feedback', models.IntegerField(max_length=225)),
                ('terakhir_online', models.DateField(max_length=225)),
                ('bergabung', models.DateField(max_length=225)),
                ('waktu_kirim_pesan', models.IntegerField(max_length=225)),
                ('jumlah_pengikut', models.IntegerField(max_length=225)),
            ],
        ),
    ]
