# Generated by Django 2.2.5 on 2019-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuankredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuankredit',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
